# Usar una imagen oficial de Python
FROM python:3.9-slim

# Instalar dependencias del sistema necesarias, incluyendo Ollama
RUN apt-get update && apt-get install -y \
    curl \
    && curl -sSL https://ollama.com/install.sh | bash \
    && apt-get clean

ENV PATH="/root/.local/bin:${PATH}"

# Entorno de trabajo
WORKDIR /app

# Copiar los archivos del proyecto al contenedor
COPY . .

# requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Exponer el puerto de Flask
EXPOSE 5001

# Comando para ejecutar la app
CMD ["python", "app.py"]
