version: "3.9"

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama  # Ayuda a identificarlo
    ports:
      - "11434:11434"  # Puerto de ollama
    volumes:
      - ollama_data:/root/.ollama  # Volumen para datos de Ollama
      - models:/app/models      # Volumen para los modelos
    networks:
      - my-network  #  Misma red para ambos contenedores

  flask:
    build:
      context: .
      dockerfile: Dockerfile-flask
    ports:
      - "5001:5001"
    depends_on:
      - ollama
    environment:
      OLLAMA_URL: http://ollama:11434  # Usa el nombre del servicio 'ollama'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Docker dentro del contenedor Flask
      - models:/app/models  # Montar los volúmenes
      - db_data:/app/data
      - ./static:/app/static  
      - ./templates:/app/templates
    networks:
      - my-network  # Usa la misma red que Ollama

networks:
  my-network:  #

volumes:
  ollama_data:  # Volumen para datos de Ollama
  models:      # Volumen para los modelos
  db_data: